#ifndef GPIO_INTERRUPT_H
#define GPIO_INTERRUPT_H

void GPIO_IRQHandler(void);

#define GM_PULSE	FL_GPIO_EXTI_LINE_2
#define POWER_BTN	FL_GPIO_EXTI_LINE_4
#define USB_SENSE	FL_GPIO_EXTI_LINE_6
#define MENU_BTN	FL_GPIO_EXTI_LINE_10


#endif // GPIO_INTERRUPT_H